{% set name = "aws-cdk.aws-ecs" %}
{% set version = "1.204.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/aws-cdk.aws-ecs-{{ version }}.tar.gz
  sha256: 9d324cdd016141560ce59b3924ba93327d15ed4f9efb179bceae18c157f9a199

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=67.3.2,<67.4.dev0
    - wheel >=0.40,<1.dev0
    - pip
  run:
    - python >={{ python_min }}
    - aws-cdk.aws-applicationautoscaling ==1.204.0
    - aws-cdk.aws-autoscaling-hooktargets ==1.204.0
    - aws-cdk.aws-autoscaling ==1.204.0
    - aws-cdk.aws-certificatemanager ==1.204.0
    - aws-cdk.aws-cloudwatch ==1.204.0
    - aws-cdk.aws-ec2 ==1.204.0
    - aws-cdk.aws-ecr-assets ==1.204.0
    - aws-cdk.aws-ecr ==1.204.0
    - aws-cdk.aws-elasticloadbalancing ==1.204.0
    - aws-cdk.aws-elasticloadbalancingv2 ==1.204.0
    - aws-cdk.aws-iam ==1.204.0
    - aws-cdk.aws-kms ==1.204.0
    - aws-cdk.aws-lambda ==1.204.0
    - aws-cdk.aws-logs ==1.204.0
    - aws-cdk.aws-route53-targets ==1.204.0
    - aws-cdk.aws-route53 ==1.204.0
    - aws-cdk.aws-s3-assets ==1.204.0
    - aws-cdk.aws-s3 ==1.204.0
    - aws-cdk.aws-secretsmanager ==1.204.0
    - aws-cdk.aws-servicediscovery ==1.204.0
    - aws-cdk.aws-sns ==1.204.0
    - aws-cdk.aws-sqs ==1.204.0
    - aws-cdk.aws-ssm ==1.204.0
    - aws-cdk.core ==1.204.0
    - aws-cdk.cx-api ==1.204.0
    - constructs >=3.3.69,<4.0.0
    - python-jsii >=1.84.0,<2.0.0
    - publication >=0.0.3
    - typeguard >=2.13.3,<2.14.dev0

test:
  imports:
    - aws_cdk.aws_ecs
    - aws_cdk.aws_ecs._jsii
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/aws/aws-cdk
  summary: The CDK Construct Library for AWS::ECS
  dev_url: https://github.com/aws/aws-cdk.git
  license: Apache-2.0
  license_file:
    - NOTICE
    - LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
